# Generated by Django 3.2.24 on 2024-03-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_word_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='words',
        ),
    ]
