# Generated by Django 3.2.24 on 2024-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_topic_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='words',
            field=models.ManyToManyField(to='main.Word'),
        ),
    ]
