# Generated by Django 3.2.24 on 2024-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topic_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='words',
            field=models.ManyToManyField(related_name='topics', to='main.Word'),
        ),
    ]
