# Generated by Django 3.2.24 on 2024-03-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_topic_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic_title',
        ),
    ]
